export enum AuditAction {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  UPDATE_STATUS = 'UPDATE_STATUS',
  DELETE = 'DELETE',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
}
