@baseUrl = http://localhost:3001

### REGISTER
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "name": "João da Silva",
  "email": "user01@gmail.com",
  "password": "123456"

}

### LOGIN
POST {{baseUrl}}/auth/singin
Content-Type: application/json

{
  "email": "admin@demo.com",
  "password": "Admin@123"
}

### ME
GET {{baseUrl}}/me