@baseUrl = http://localhost:3001
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2FvLWRhLXNpbHZhNDE2NDYzIiwiZW1haWwiOiJ1c2VyMDJAZ21haWwuY29tIiwibmFtZSI6Ikpvw6NvIGRhIFNpbHZhIiwiaWF0IjoxNzg1MjM5OTA2LCJleHAiOjE3ODUzMjYzMDZ9.y_dKsjCtRK9pKmfF0Ar5Zh2YuqNce6E1Nf3qOqYr6as

@tweetId=4

### ADD TWEET
POST {{baseUrl}}/tweet
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "body": "Olá sou novo por aqui!"
}

### SEARCH TWEET
GET {{baseUrl}}/tweet/search?page=1&limit=10&q=estu
Authorization: Bearer {{token}}

### FIND TWEET BY ID
GET {{baseUrl}}/tweet/{{tweetId}}
Authorization: Bearer {{token}}

### GET ANSWERS
GET {{baseUrl}}/tweet/{{tweetId}}/answers
Authorization: Bearer {{token}}

### LIKED 
POST  {{baseUrl}}/tweet/{{tweetId}}/like
Content-Type: application/json
Authorization: Bearer {{token}}
