@baseUrl = http://localhost:3001
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2FvLWRhLXNpbHZhNzIwOSIsImVtYWlsIjoidXNlcjAxQGdtYWlsLmNvbSIsIm5hbWUiOiJHaW92YW5lIFJpY2hhcmQiLCJpYXQiOjE3ODUyNDAxNDIsImV4cCI6MTc4NTMyNjU0Mn0.oOFz-R-oVThDPXBrAvFNYk2bWUcjA44KIps81P1cfbo
@slug = joao-da-silva7209
@slug2 = joao-da-silva416463

### GET SUGGESTIONS USER
GET {{baseUrl}}/user/suggestions
Authorization: Bearer {{token}}

### GET USER BY SLUG
GET {{baseUrl}}/user/{{slug}}
Authorization: Bearer {{token}}

### GET TWEETS TO THE USER BY SLUG
GET {{baseUrl}}/user/{{slug}}/tweets?page=1&limit=10
Authorization: Bearer {{token}}

### GET TWEETS TO THE USER BY SLUG
POST {{baseUrl}}/user/{{slug}}/follow
Content-Type: application/json
Authorization: Bearer {{token}}

### UPDATE USER INFO
PATCH  {{baseUrl}}/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Giovane Richard",
  "bio": "Estou testando os dados da minha bio",
  "link": "https://www.youtube.com/@giovanerichard171"
}